import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, '..')

function readDefinedValue(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim() !== '') {
      return value.trim()
    }
  }

  return undefined
}

function normalizeBasePath(basePath) {
  if (!basePath || basePath === '/') {
    return '/'
  }

  const normalized = `/${basePath.replace(/^\/+|\/+$/gu, '')}/`
  return normalized
}

function resolveCallbackPath(basePath) {
  const normalizedBasePath = normalizeBasePath(basePath)

  if (normalizedBasePath === '/') {
    return '/auth/callback'
  }

  return `${normalizedBasePath.slice(0, -1)}/auth/callback`
}

function normalizeOrigin(origin, fallbackOrigin, label) {
  const explicitOrigin = readDefinedValue(origin)
  const candidate = explicitOrigin ?? fallbackOrigin

  if (!candidate) {
    return undefined
  }

  try {
    return new URL(candidate).origin
  } catch {
    if (explicitOrigin) {
      throw new Error(`Invalid ${label}: ${explicitOrigin}`)
    }

    return fallbackOrigin
  }
}

function parseEnvFile(content) {
  const entries = {}

  for (const rawLine of content.split(/\r?\n/u)) {
    const line = rawLine.trim()

    if (!line || line.startsWith('#')) {
      continue
    }

    const separatorIndex = line.indexOf('=')

    if (separatorIndex === -1) {
      continue
    }

    const key = line.slice(0, separatorIndex).trim()
    let value = line.slice(separatorIndex + 1).trim()

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    entries[key] = value
  }

  return entries
}

async function readOptionalFile(filePath) {
  try {
    await access(filePath)
    return await readFile(filePath, 'utf8')
  } catch {
    return ''
  }
}

function ensureAuthCallback(urlString, fallbackBase, basePath = '/') {
  const callbackPath = resolveCallbackPath(basePath)
  const fallback = new URL(callbackPath, fallbackBase).toString()

  if (!readDefinedValue(urlString)) {
    return fallback
  }

  try {
    const url = new URL(urlString)
    url.pathname = callbackPath
    url.search = ''
    url.hash = ''
    return url.toString()
  } catch {
    return fallback
  }
}

function toEnvFile(entries) {
  return [
    '# Generated by scripts/sync-env.mjs',
    ...Object.entries(entries).map(([key, value]) => `${key}=${value}`),
    ''
  ].join('\n')
}

async function main() {
  const exampleEnvPath = path.join(rootDir, '.env.example')
  const localEnvPath = path.join(rootDir, '.env')

  const exampleEnv = parseEnvFile(await readOptionalFile(exampleEnvPath))
  const localEnv = parseEnvFile(await readOptionalFile(localEnvPath))
  const mergedEnv = { ...exampleEnv, ...localEnv }

  const basePath = readDefinedValue(mergedEnv.VITE_BASE_URL) ?? '/'
  const webOrigin =
    normalizeOrigin(mergedEnv.WEB_ORIGIN, 'http://localhost:5173', 'WEB_ORIGIN') ??
    'http://localhost:5173'
  const apiOrigin =
    normalizeOrigin(mergedEnv.API_ORIGIN, 'http://localhost:3001', 'API_ORIGIN') ??
    'http://localhost:3001'
  const callbackUrl = ensureAuthCallback(
    readDefinedValue(mergedEnv.SSO_REDIRECT, mergedEnv.VITE_SSO_REDIRECT),
    webOrigin,
    basePath
  )

  const normalizedEnv = {
    NODE_ENV: readDefinedValue(mergedEnv.NODE_ENV) ?? 'development',
    PORT: readDefinedValue(mergedEnv.PORT) ?? '3001',
    API_ORIGIN: apiOrigin,
    WEB_ORIGIN: webOrigin,
    DATABASE_URL: readDefinedValue(mergedEnv.DATABASE_URL) ?? '',
    COOKIE_NAME: readDefinedValue(mergedEnv.COOKIE_NAME) ?? 'sid',
    COOKIE_SECURE: readDefinedValue(mergedEnv.COOKIE_SECURE) ?? 'false',
    SESSION_TTL_SECONDS: readDefinedValue(mergedEnv.SESSION_TTL_SECONDS) ?? '604800',
    SSO_URL: readDefinedValue(mergedEnv.SSO_URL, mergedEnv.VITE_SSO_URL) ?? '',
    SSO_ID: readDefinedValue(mergedEnv.SSO_ID, mergedEnv.VITE_SSO_ID) ?? '',
    SSO_SECRET: readDefinedValue(mergedEnv.SSO_SECRET) ?? '',
    SSO_REDIRECT: callbackUrl,
    SSO_MOCK_ENABLED: readDefinedValue(mergedEnv.SSO_MOCK_ENABLED) ?? 'true',
    SSO_MOCK_TICKET_PREFIX: readDefinedValue(mergedEnv.SSO_MOCK_TICKET_PREFIX) ?? 'mock:',
    VITE_API_BASE_URL:
      normalizeOrigin(mergedEnv.VITE_API_BASE_URL, apiOrigin, 'VITE_API_BASE_URL') ?? apiOrigin,
    VITE_SSO_URL: readDefinedValue(mergedEnv.VITE_SSO_URL, mergedEnv.SSO_URL) ?? '',
    VITE_SSO_ID: readDefinedValue(mergedEnv.VITE_SSO_ID, mergedEnv.SSO_ID) ?? '',
    VITE_BASE_URL: normalizeBasePath(basePath),
    VITE_SSO_REDIRECT: ensureAuthCallback(
      readDefinedValue(mergedEnv.VITE_SSO_REDIRECT, mergedEnv.SSO_REDIRECT),
      webOrigin,
      basePath
    )
  }

  const webEnv = Object.fromEntries(
    Object.entries(normalizedEnv).filter(([key]) => key.startsWith('VITE_'))
  )

  const apiEnv = Object.fromEntries(
    Object.entries(normalizedEnv).filter(
      ([key]) => !key.startsWith('VITE_') || key === 'VITE_BASE_URL'
    )
  )

  const webEnvPath = path.join(rootDir, 'apps/web/.env.local')
  const apiEnvPath = path.join(rootDir, 'apps/api/.env')

  await mkdir(path.dirname(webEnvPath), { recursive: true })
  await mkdir(path.dirname(apiEnvPath), { recursive: true })

  await writeFile(webEnvPath, toEnvFile(webEnv), 'utf8')
  await writeFile(apiEnvPath, toEnvFile(apiEnv), 'utf8')

  console.log(`Synced environment to ${path.relative(rootDir, webEnvPath)} and ${path.relative(rootDir, apiEnvPath)}`)
}

await main()
